export const ADD_NEW_ROW = "ADD_NEW_ROW";
export const UPDATE_AMOUNT = "UPDATE_AMOUNT";
export const UPDATE_DETAILS = "UPDATE_DETAILS";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const TOTAL_INCOME = "TOTAL_INCOME";
export const UPDATE_PERCENTAGE = "UPDATE_PERCENTAGE";
